switch3g/4g, wan.c: Updated modem's recognition, maybe at last time detection will be quicker

diff --git a/release/src-rt-6.x.4708/router/others/switch4g b/release/src-rt-6.x.4708/router/others/switch4g
--- a/release/src-rt-6.x.4708/router/others/switch4g
+++ b/release/src-rt-6.x.4708/router/others/switch4g
@@ -48,135 +48,132 @@ connect() {
 
         #we try use last diag iface first. If it failed then we try use any other ttyUSB device
         TTY=`ls /dev/ttyUSB* | grep -v $DEV`
-        DEVS="$DEV $TTY"
+        DEVS="$DEV $TTY $DEV $TTY $DEV $TTY"  # let's triple this (try 3x on every interface)
 
-        while [ "$CONNECTED" == "0" ]; do
+        while [ "$CONNECTED" -eq 0 ]; do
             for i in $DEVS; do
-                if [ "$COUNT" -lt 5 ]; then
 
-                    #disconnect first
-                    MODE="AT^NDISDUP=1,0" gcom -d $i -s /etc/gcom/setmode.gcom
-                    sleep 3
+                #disconnect first
+                MODE="AT^NDISDUP=1,0" gcom -d "$i" -s /etc/gcom/setmode.gcom
+                sleep 3
 
-                    #change network type if required
-                    MODE="AT^SYSCFGEX?" gcom -d $i -s /etc/gcom/setverbose.gcom > /tmp/4g.mode
+                # check for current type of network
+                MODE="AT^SYSCFGEX?" gcom -d "$i" -s /etc/gcom/setverbose.gcom > /tmp/4g.mode
 
-                    RESULT=`cat /tmp/4g.mode | grep SYSCFGEX | grep '"' | cut -d '"' -f2`
-                    RESROAM=`cat /tmp/4g.mode | grep SYSCFGEX | grep ',' | cut -d ',' -f3`
-                    RESBAND=`cat /tmp/4g.mode | grep SYSCFGEX | grep ',' | cut -d ',' -f5 | tr -d '\r'`
+                RESULT=`cat /tmp/4g.mode | grep SYSCFGEX | grep '"' | cut -d '"' -f2`
+                RESROAM=`cat /tmp/4g.mode | grep SYSCFGEX | grep ',' | cut -d ',' -f3`
+                RESBAND=`cat /tmp/4g.mode | grep SYSCFGEX | grep ',' | cut -d ',' -f5 | tr -d '\r'`
 
-                    case "$RESULT" in
-                         "00")   RES1="Auto" ;;
-                         "03")   RES1="4G only" ;;
-                         "02")   RES1="3G only" ;;
-                         "0302") RES1="4G/3G only" ;;
-                         "030201") RES1="4G/3G/2G" ;;
-                         *) RES1="unknown" ;;
-                    esac
+                case "$RESULT" in
+                     "00")   RES1="Auto" ;;
+                     "03")   RES1="4G only" ;;
+                     "02")   RES1="3G only" ;;
+                     "0302") RES1="4G/3G only" ;;
+                     "030201") RES1="4G/3G/2G" ;;
+                     *) RES1="unknown" ;;
+                esac
 
-                    case "$SPEED" in
-                         "00")   SPD1="Auto" ;;
-                         "03")   SPD1="4G only" ;;
-                         "02")   SPD1="3G only" ;;
-                         "0302") SPD1="4G/3G only" ;;
-                         "030201") SPD1="4G/3G/2G" ;;
-                         *) SPD1="unknown" ;;
-                    esac
+                case "$SPEED" in
+                     "00")   SPD1="Auto" ;;
+                     "03")   SPD1="4G only" ;;
+                     "02")   SPD1="3G only" ;;
+                     "0302") SPD1="4G/3G only" ;;
+                     "030201") SPD1="4G/3G/2G" ;;
+                     *) SPD1="unknown" ;;
+                esac
 
-                    case "$RESROAM" in
-                         "0")  RES3="Disabled"  ;;
-                         "1")  RES3="Supported" ;;
-                         "2")  RES3="No change" ;;
-                         "3")  RES3="Roam only" ;;
-                         *)    RES3="unknown"   ;;
-                    esac
+                case "$RESROAM" in
+                     "0")  RES3="Disabled"  ;;
+                     "1")  RES3="Supported" ;;
+                     "2")  RES3="No change" ;;
+                     "3")  RES3="Roam only" ;;
+                     *)    RES3="unknown"   ;;
+                esac
 
-                    case "$ROAMING" in
-                         "0")  ROAM3="Disabled"  ;;
-                         "1")  ROAM3="Supported" ;;
-                         "2")  ROAM3="No change" ;;
-                         "3")  ROAM3="Roam only" ;;
-                         *)    ROAM3="unknown"   ;;
-                    esac
+                case "$ROAMING" in
+                     "0")  ROAM3="Disabled"  ;;
+                     "1")  ROAM3="Supported" ;;
+                     "2")  ROAM3="No change" ;;
+                     "3")  ROAM3="Roam only" ;;
+                     *)    ROAM3="unknown"   ;;
+                esac
 
-                    case "$RESBAND" in
-                         "80000") RES2="B20 (800 MHz)" ;;
-                         "4")     RES2="B3 (1800 MHz)" ;;
-                         "1")     RES2="B1 (2100 MHz)" ;;
-                         "40")    RES2="B7 (2600 MHz)" ;;
-                         "7FFFFFFFFFFFFFFF") RES2="All supported" ;;
-                         *)       RES2="unknown"       ;;
-                    esac
+                case "$RESBAND" in
+                     "80000") RES2="B20 (800 MHz)" ;;
+                     "4")     RES2="B3 (1800 MHz)" ;;
+                     "1")     RES2="B1 (2100 MHz)" ;;
+                     "40")    RES2="B7 (2600 MHz)" ;;
+                     "7FFFFFFFFFFFFFFF") RES2="All supported" ;;
+                     *)       RES2="unknown"       ;;
+                esac
 
-                    case "$BAND" in
-                         "80000") BAND2="B20 (800 MHz)" ;;
-                         "4")     BAND2="B3 (1800 MHz)" ;;
-                         "1")     BAND2="B1 (2100 MHz)" ;;
-                         "40")    BAND2="B7 (2600 MHz)" ;;
-                         "7FFFFFFFFFFFFFFF") BAND2="All supported" ;;
-                         *)       BAND2="unknown"       ;;
-                    esac
+                case "$BAND" in
+                     "80000") BAND2="B20 (800 MHz)" ;;
+                     "4")     BAND2="B3 (1800 MHz)" ;;
+                     "1")     BAND2="B1 (2100 MHz)" ;;
+                     "40")    BAND2="B7 (2600 MHz)" ;;
+                     "7FFFFFFFFFFFFFFF") BAND2="All supported" ;;
+                     *)       BAND2="unknown"       ;;
+                esac
 
-                    # change band and roaming  /pedro
-                    if [ "$RESULT" != "$SPEED" ]; then
-                        TXTLOG="Network type changed: was $RES1, now $SPD1."
-                        MODESPEED=$SPEED
-                    else
-                        TXTLOG="Network type is $RES1."
-                        MODESPEED=$RESULT
-                    fi
-                    if [ "$ROAMING" != "$RESROAM" ]; then
-                        TXTLOG="$TXTLOG Roaming changed: was '$RES3', now '$ROAM3'."
-                        MODEROAM=$ROAMING
-                    else
-                        TXTLOG="$TXTLOG Roaming is '$RES3'."
-                        MODEROAM=$RESROAM
-                    fi
-                    if [ "$SPEED" == "03" -a "$BAND" != "$RESBAND" ]; then
-                        TXTLOG="$TXTLOG Band changed: was '$RES2', now '$BAND2'."
-                        MODEBAND=$BAND
-                    else
-                        TXTLOG="$TXTLOG Band is '$RES2'."
-                        MODEBAND=$RESBAND
-                    fi
+                # change network type, band and roaming if required
+                if [ "$RESULT" != "$SPEED" ]; then
+                    TXTLOG="Network type changed: was $RES1, now $SPD1."
+                    MODESPEED=$SPEED
+                else
+                    TXTLOG="Network type is $RES1."
+                    MODESPEED=$RESULT
+                fi
+                if [ "$ROAMING" != "$RESROAM" ]; then
+                    TXTLOG="$TXTLOG Roaming changed: was '$RES3', now '$ROAM3'."
+                    MODEROAM=$ROAMING
+                else
+                    TXTLOG="$TXTLOG Roaming is '$RES3'."
+                    MODEROAM=$RESROAM
+                fi
+                if [ "$SPEED" == "03" -a "$BAND" != "$RESBAND" ]; then
+                    TXTLOG="$TXTLOG Band changed: was '$RES2', now '$BAND2'"
+                    MODEBAND=$BAND
+                else
+                    TXTLOG="$TXTLOG Band is '$RES2'"
+                    MODEBAND=$RESBAND
+                fi
 
-                    logger -t switch4g[$PID] "4G MODEM - $TXTLOG (device $i)"
+                logger -t switch4g[$PID] "4G MODEM - $TXTLOG (device $i)"
 
 
-                    if [ "$RESULT" != "$SPEED" ] ||  [ "$ROAMING" != "$RESROAM" ] || ([ "$SPEED" == "03" ] && [ "$BAND" != "$RESBAND" ]); then
-                        MODE="AT^SYSCFGEX=\"$MODESPEED\",3fffffff,$MODEROAM,4,$MODEBAND,," gcom -d $i -s /etc/gcom/setverbose.gcom
-                        sleep 5
-                    fi
+                if [ "$RESULT" != "$SPEED" ] ||  [ "$ROAMING" != "$RESROAM" ] || ([ "$SPEED" == "03" ] && [ "$BAND" != "$RESBAND" ]); then
+                    MODE="AT^SYSCFGEX=\"$MODESPEED\",3fffffff,$MODEROAM,4,$MODEBAND,," gcom -d "$i" -s /etc/gcom/setverbose.gcom
+                    sleep 5
+                fi
 
-                    #connect
-                    MODE="AT^NDISDUP=1,1,\"$APN\"" gcom -d $i -s /etc/gcom/setverbose.gcom
-                    sleep 3
+                #connect
+                MODE="AT^NDISDUP=1,1,\"$APN\"" gcom -d "$i" -s /etc/gcom/setverbose.gcom
+                sleep 3
 
-                    MODE="AT+CGPADDR=1" gcom -d $i -s /etc/gcom/setverbose.gcom > /tmp/4g.mode
+                MODE="AT+CGPADDR=1" gcom -d "$i" -s /etc/gcom/setverbose.gcom > /tmp/4g.mode
 
-                    CHECK=`cat /tmp/4g.mode | grep "+CGPADDR:" | cut -d '"' -f2 | wc -l`
-                    if [ "$CHECK" == "1" ]; then
-                        logger -t switch4g[$PID] "4G MODEM - connected (device $i) ..."
-                        CONNECTED=1
-                        COUNT=6
-                        nvram set modem_dev4g="$i"
-                        break
-                    else
-                        logger -t switch4g[$PID] "4G MODEM - connection failed (device $i) [$COUNT]"
-                        sleep 5
-                        COUNT=`expr $COUNT + 1`
-                    fi
+                CHECK=`cat /tmp/4g.mode | grep "+CGPADDR:" | cut -d '"' -f2 | wc -l`
+                if [ "$CHECK" -eq 1 ]; then
+                    logger -t switch4g[$PID] "4G MODEM - connected (device $i) ..."
+                    CONNECTED=1
+                    nvram set modem_dev4g="$i"
+                    break
+                else
+                    logger -t switch4g[$PID] "4G MODEM - connection failed (device $i) [$COUNT]"
+                    COUNT=`expr $COUNT + 1`
+                    sleep 5
                 fi
             done
 
             # checked all devices but still not connected?
-            if [ "$CONNECTED" == "0" ]; then
+            if [ "$CONNECTED" -eq 0 ]; then
 
                 INTERVAL=`nvram get mwan_cktime`
                 if [ "$INTERVAL" -gt 0 ]; then
                     logger -t switch4g[$PID] "4G MODEM - connection failed - watchdog enabled"
 
-                    # try to redetect and connect again in next cycle /pedro
+                    # try to redetect and connect again in next cycle
                     rm -f $READYFILE > /dev/null 2>&1
                     watchdog add
                 else
@@ -218,7 +215,7 @@ connect() {
         esac
  
         # set roaming
-        if [ "$ROAMING" == "0" -o "$ROAMING" == "1" -o "$ROAMING" == "3" ]; then
+        if [ "$ROAMING" -eq 0 -o "$ROAMING" -eq 1 -o "$ROAMING" -eq 3 ]; then
             uqmi -s -d "$DEV" --set-network-roaming "$ROAM3"
             logger -t switch4g[$PID] "4G MODEM - Roaming is set to '$ROAM3'"
             sleep 2
@@ -233,7 +230,7 @@ connect() {
 
         CONNECTED=0
         COUNT=0
-        while [ $CONNECTED == "0" ]; do
+        while [ "$CONNECTED" -eq 0 ]; do
             if [ "$COUNT" -lt 5 ]; then
 
                 if [ "$CLID" != "" ]; then
@@ -243,8 +240,8 @@ connect() {
                     case $PDH in
                     ''|*[!0-9]*)
                         logger -t switch4g[$PID] "4G MODEM - connection failed (device $DEV) [$COUNT]"
-                        sleep 5
                         COUNT=`expr $COUNT + 1`
+                        sleep 5
                         ;;
                     *)
                         logger -t switch4g[$PID] "4G MODEM - connected (device $DEV) ..."
@@ -281,16 +278,16 @@ connect() {
     DONE=0
     COUNT=1
 
-    while [ $DONE = "0" ]; do
+    while [ "$DONE" -eq 0 ]; do
         if [ "$COUNT" -lt 5 ]; then
 
             dhcpc-release $PREFIX
             sleep 1
             dhcpc-renew $PREFIX
 
-            CHECKIFA=`ifconfig | grep $IFA | wc -l`
-            if [ "$CHECKIFA" == "1" ]; then
-                # wan-up fix /pedro
+            CHECKIFA=`ifconfig | grep "$IFA" | wc -l`
+            if [ "$CHECKIFA" -eq 1 ]; then
+                # wan-up fix
                 dhcpc-release $PREFIX
                 sleep 1
                 dhcpc-renew $PREFIX
@@ -303,7 +300,7 @@ connect() {
             else
                 logger -t switch4g[$PID] "4G MODEM - WAN IFACE not ready ($IFA) [$COUNT]"
                 COUNT=`expr $COUNT + 1`
-                sleep 5
+                sleep 4
             fi
         else
             INTERVAL=`nvram get mwan_cktime`
@@ -330,7 +327,7 @@ disconnect() {
     dhcpc-release $PREFIX
 
     if [ "$TYPE" == "non-hilink" -o "$TYPE" == "hw-ether" ]; then
-        MODE="AT^NDISDUP=1,0" gcom -d $DEV -s /etc/gcom/setmode.gcom
+        MODE="AT^NDISDUP=1,0" gcom -d "$DEV" -s /etc/gcom/setmode.gcom
         sleep 1
     elif [ "$TYPE" == "qmi_wwan" ]; then
         # disable previous autoconnect state using the global handle
@@ -377,7 +374,7 @@ setPIN() {
     PIN=`nvram get "$PREFIX"_modem_pin`
     IS_PIN=`nvram get "$PREFIX"_modem_pin | wc -w`
 
-    if [ "$IS_PIN" == "1" ]; then #only for non-hilink
+    if [ "$IS_PIN" -eq 1 ]; then #only for non-hilink
 
         if [ "$TYPE" == "non-hilink" -o "$TYPE" == "hw-ether" ]; then
             #we try use last diag iface first. If it failed then we try use any other ttyUSB device
@@ -422,10 +419,12 @@ switchMode() {
         modprobe -r $MODULE
     done
 
+    logger -t switch4g[$PID] "4G MODEM - detecting ..."
+
     COUNT=0
     FOUND=0
 
-    while [ $FOUND == "0" ]; do
+    while [ $FOUND -eq 0 ]; do
         #modem not found, try to detect
         DEVICES=`lsusb | awk '{print $6}'`
 
@@ -434,11 +433,14 @@ switchMode() {
 
             # vendor:product
 
-            if [ "$SEARCH" == "1" ]; then
+            if [ "$SEARCH" -eq 1 ]; then
                 logger -t switch4g[$PID] "4G MODEM FOUND - $SWITCH - Switching ..."
                 DV=`echo $SWITCH | cut -d ":" -f1`
                 DP=`echo $SWITCH | cut -d ":" -f2`
                 /usr/sbin/usb_modeswitch -Q -c /etc/usb_modeswitch.d/$SWITCH -v $DV -p $DP
+
+                # need few seconds before modem will be detected once again after switch
+                sleep 6
 
                 VENDOR=`cat /etc/usb_modeswitch.d/$SWITCH | grep "TargetVendor" | cut -d "=" -f2 | cut -d "x" -f2`
                 if [ "$VENDOR" == "" ]; then
@@ -449,20 +451,14 @@ switchMode() {
                 if [ "$PRODUCT" != "" ]; then
                     logger -t switch4g[$PID] "4G MODEM ready - $VENDOR:$PRODUCT"
                     echo "$VENDOR:$PRODUCT" > $DETECTFILE
-                # why not?
-                #else
-                    #PRODUCT=`echo $SWITCH | cut -d ":" -f2`
                 fi
             fi
         done
 
-        #need few seconds before modem will be detected once again after switch
-        sleep 10
-
         # is modem ready?
         for MODULE in $MODULES; do
             modprobe $MODULE
-            sleep 2
+            sleep 1
 
             SEARCH=`cat /proc/bus/usb/devices | grep Driver | grep $MODULE | wc -l`
 
@@ -484,7 +480,7 @@ switchMode() {
                 FOUND=1
                 break
             else
-                if [ "$COUNT" == "5" ]; then
+                if [ "$COUNT" -eq 5 ]; then
                     logger -t switch4g[$PID] "4G MODEM NDIS not found - process terminated!"
                     rm -f $PIDFILE > /dev/null 2>&1
                     exit 0
@@ -492,7 +488,7 @@ switchMode() {
                     logger -t switch4g[$PID] "4G MODEM NDIS ($MODULE) not found [$COUNT] ..."
                     modprobe -r $MODULE
                     COUNT=`expr $COUNT + 1`
-                    sleep 5
+                    sleep 3
                 fi
             fi
         done
@@ -507,7 +503,7 @@ searchWAN() {
 
     KERNEL=`uname -r | cut -d "." -f1,2,3`
 
-    while [ $FOUND == "0" ]; do
+    while [ "$FOUND" -eq 0 ]; do
         if [ "$TYPE" == "hw-ether" ]; then
             WAN=`dmesg | grep huawei_ether | grep Device | grep register | cut -d ":" -f1 | tail -1`
         elif [ "$KERNEL" == "2.6.36" ]; then #ARM
@@ -521,11 +517,11 @@ searchWAN() {
         if [ "$IS_WAN" -gt 0 ]; then
             logger -t switch4g[$PID] "4G MODEM WAN ($TYPE) found - using $WAN as WAN"
             nvram set wan_4g="$WAN"
-            nvram set modem_type=$TYPE
+            nvram set modem_type="$TYPE"
             FOUND=1
             echo "$WAN" > $READYFILE
         else
-            if [ "$COUNT" == "5" ]; then
+            if [ "$COUNT" -eq 5 ]; then
                 logger -t switch4g[$PID] "4G MODEM WAN not found - connection process terminated!"
                 rm -f $PIDFILE > /dev/null 2>&1
                 exit 0
@@ -556,7 +552,7 @@ searchDiag() {
                     modprobe -r usbserial
                     insmod usbserial vendor=0x$VENDOR product=0x$PRODUCT
                     echo "$VENDOR:$PRODUCT" > $DETECTFILE
-                    sleep 2
+                    sleep 1
                 fi
             fi
 
@@ -569,12 +565,12 @@ searchDiag() {
                 #last change. try load usbserial for each usb devices
                 DEVICES=`lsusb | awk '{print $6}'`
                 for SWITCH in $DEVICES; do
-                    if [ "$FOUND" == "0" ]; then
+                    if [ "$FOUND" -eq 0 ]; then
                         VENDOR=`echo $SWITCH | cut -d ":" -f1`
                         PRODUCT=`echo $SWITCH | cut -d ":" -f2`
                         modprobe -r usbserial
                         insmod usbserial vendor=0x$VENDOR product=0x$PRODUCT
-                        sleep 2
+                        sleep 1
 
                         DEV=`cat /proc/bus/usb/devices | grep Driver | grep usbserial | wc -l`
                         if [ "$DEV" -gt 0 ]; then
@@ -590,14 +586,14 @@ searchDiag() {
         fi
 
         #search diagnostic device
-        sleep 1
+        sleep 5
         TTY=`ls /dev/ttyUSB*`
 
         for i in $TTY; do
-            CHECKTTY=`gcom -d $i -s /etc/gcom/getcardinfo.gcom | grep OK | wc -l`
+            CHECKTTY=`gcom -d "$i" -s /etc/gcom/getcardinfo.gcom | grep OK | wc -l`
             if [ "$CHECKTTY" == "1" ]; then #found working interface
                 logger -t switch4g[$PID] "4G MODEM DIAG found (device $i)"
-                nvram set modem_dev4g=$i
+                nvram set modem_dev4g="$i"
                 DEVNR=$i
             else
                 logger -t switch4g[$PID] "4G MODEM DIAG not found"
@@ -610,9 +606,9 @@ searchDiag() {
 
         for i in $TTY; do
             CHECKTTY=`uqmi -s -d "$i" --get-versions | grep service | wc -l`
-            if [ "$CHECKTTY" == "1" ]; then #found working interface
+            if [ "$CHECKTTY" -eq 1 ]; then #found working interface
                 logger -t switch4g[$PID] "4G MODEM DIAG found (device $i)"
-                nvram set modem_dev4g=$i
+                nvram set modem_dev4g="$i"
                 DEVNR=$i
             else
                 logger -t switch4g[$PID] "4G MODEM DIAG not found"
