switch3g: rework (1/2)
- preparation for multimodem feature
- update of "switchMode" function: check for change of "bNumInterfaces" - speeds up/improves detection
- update of "searchDiag" function: use DEVICENAME for DIAG check
- yet incomplete (no auto DIAGS function) but it's working...

diff --git a/release/src-rt-6.x.4708/router/others/switch3g b/release/src-rt-6.x.4708/router/others/switch3g
--- a/release/src-rt-6.x.4708/router/others/switch3g
+++ b/release/src-rt-6.x.4708/router/others/switch3g
@@ -3,238 +3,299 @@
 #
 # Copyright (C) 2011 shibby
 #
+# changes/fixes: 2018 by pedro
+#
 
 
-PREFIX=$1
+PREFIX="$1"
 
 PID=$$
-PIDFILE="/var/run/switch3g.pid"
-DETECTFILE="/tmp/3g.detect"
-MODE=`nvram get "$PREFIX"_proto`
-DEVNR=`nvram get "$PREFIX"_modem_dev`
+PIDFILE="/var/run/switch3g_$PREFIX.pid"
+DIAGSFILE="/tmp/switch3g_$PREFIX.diags"
+MODE=$(nvram get "$PREFIX"_proto)
+DEVNR=$(nvram get "$PREFIX"_modem_dev)
+LOGS="logger -t switch3g[$PID]"
 
 
-if [ -z "$PREFIX" ]; then
-    echo "usage: switch3g INTERFACE"
-    exit 0
-fi
+[ -z "$PREFIX" ] && {
+	echo "usage: switch3g INTERFACE [signal]"
+	exit 0
+}
 
-if [ "$MODE" == "lte" ]; then
-    exit 0
-fi
+[ ! "$MODE" == "ppp3g" ] && {
+	exit 0
+}
 
 
 switchMode() {
-    logger -t switch3g[$PID] "3G MODEM - detecting ..."
+	VENDOR="" PRODUCT="" MODULE="" DEVICENAME="" TTYS="" ALREADYFOUND=0	# global
+	local COUNT=1 SWITCHED=0 DVDP=0 TTYS_PATH="" PATHDEV SWITCH DEVICES IFN_BEFORE DV DP DB DG
 
-    # check if modem is already found
-    MODULES="cdc_acm option sierra usbserial"
+	# search for DEVICENAME via active TTYs
+	for DEVICENAME in $(ls /sys/bus/usb/devices/ | grep -v ":" | grep "-"); do
 
-    for MODULE in $MODULES; do
-        if [ `cat /proc/bus/usb/devices | grep Driver | grep $MODULE | wc -l` -gt 0 ]; then
+		PATHDEV="/sys/bus/usb/devices/$DEVICENAME"
+		[ -f $PATHDEV/idVendor -a -f $PATHDEV/idProduct -a -f $PATHDEV/uevent ] || continue	# skip
 
-            MODULE=`echo $MODULE | tr "_" "-"`
+		TTYS=$(ls -d $PATHDEV/${DEVICENAME}*/tty?* 2>/dev/null | sed -e "s/.*\/\//.*/g" -e "s/.*\//\/dev\//g" | tr "\n" " " | sed -e "s/  */ /g" -e "s,^ *,,; s, *$,,")
 
-            logger -t switch3g[$PID] "3G MODEM already found - using $MODULE module"
-            nvram set 3g_module=$MODULE
-            return 1
-        fi
-    done
+		[ -n "$TTYS" ] && {
+			VENDOR=$(cat "$PATHDEV"/idVendor)
+			PRODUCT=$(cat "$PATHDEV"/idProduct)
 
-    #modem not found, try to detect it
-    DEVICES=`lsusb | awk '{print $6}'`
+			TTYS_PATH=$(ls -d $PATHDEV/${DEVICENAME}*/tty?* 2>/dev/null | sed 's/\/tty.*/\/uevent/g')
+			MODULE=$(cat $TTYS_PATH 2>/dev/null | grep ^DRIVER | cut -d "=" -f2 | head -n1)
+			findPath		# MODULE --> MPATH
+			echo "$VENDOR $PRODUCT" > $MPATH
 
-    for SWITCH in $DEVICES; do
-        SEARCH=`ls /etc/usb_modeswitch.d/$SWITCH | wc -l`
+			$LOGS "3G MODEM ready ($VENDOR:$PRODUCT) - DIAG interface(s) found ("$TTYS") - using already loaded $MODULE module"
 
-        # vendor:product
+			ALREADYFOUND=1
+			break
+		}
+	done
 
-        if [ "$SEARCH" -eq 1 ]; then
-            logger -t switch3g[$PID] "3G MODEM FOUND - $SWITCH - Switching ..."
+	[ "$ALREADYFOUND" -eq 0 ] && {
+		$LOGS "3G MODEM - detecting ..."
 
-            DV=`echo $SWITCH | cut -d ":" -f1`
-            DP=`echo $SWITCH | cut -d ":" -f2`
-            /usr/sbin/usb_modeswitch -Q -c /etc/usb_modeswitch.d/$SWITCH -v $DV -p $DP
+		# detect modem
+		DEVICES=$(lsusb | awk '{print $6}')
 
-            # need few seconds before modem will be detected once again after switch
-            sleep 8
+		for SWITCH in $DEVICES; do
+			[ "$(ls /etc/usb_modeswitch.d/"$SWITCH" 2> /dev/null | wc -l)" -eq 1 ] && {
+				# search for DEVICENAME & other data
+				for DEVICENAME in $(ls /sys/bus/usb/devices/ | grep -v ":" | grep "-"); do
+					PATHDEV="/sys/bus/usb/devices/$DEVICENAME"
+					[ -f $PATHDEV/idVendor -a -f $PATHDEV/idProduct -a -f $PATHDEV/uevent ] || continue	# skip
 
-            VENDOR=`cat /etc/usb_modeswitch.d/$SWITCH | grep "TargetVendor" | cut -d "=" -f2 | cut -d "x" -f2`
-            if [ "$VENDOR" == "" ]; then
-                VENDOR=`echo $SWITCH | cut -d ":" -f1`
-            fi
+					DV=$(cat "$PATHDEV"/idVendor)					# vendor
+					DP=$(cat "$PATHDEV"/idProduct)					# product
+					DB=$(grep -s ^BUSNUM "$PATHDEV"/uevent | cut -d "=" -f2)	# BUSNUM
+					DG=$(grep -s ^DEVNUM "$PATHDEV"/uevent | cut -d "=" -f2)	# DEVNUM
 
-            PRODUCT=`lsusb | awk '{print $6}' | grep $VENDOR | cut -d ":" -f2`
-            if [ "$PRODUCT" != "" ]; then
-               logger -t switch3g[$PID] "3G MODEM ready - $VENDOR:$PRODUCT"
-               echo "$VENDOR:$PRODUCT" > $DETECTFILE
-            fi
-        fi
-    done
+					[ "$DV" == "$(echo "$SWITCH" | cut -d ":" -f1)" -a "$DP" == "$(echo "$SWITCH" | cut -d ":" -f2)" ] && {		# self
+						DVDP=1
+						break
+					}
+				done
 
-    #trying option and sierra module first
-    modprobe cdc-acm
-    modprobe option
-    modprobe sierra
-    sleep 3
-    DEV0=`cat /proc/bus/usb/devices | grep Driver | grep cdc_acm | wc -l`
-    DEV1=`cat /proc/bus/usb/devices | grep Driver | grep option | wc -l`
-    DEV2=`cat /proc/bus/usb/devices | grep Driver | grep sierra | wc -l`
+				[ "$DVDP" -eq 1 ] && {
+					# in some cases it needs more time
+					COUNT=1
+					while [ "$COUNT" -lt 5 ]; do
+						sleep 1
+						[ -s $PATHDEV/bNumInterfaces ] && {
+							IFN_BEFORE=$(cat "$PATHDEV"/bNumInterfaces)
+							break
+						}
+						COUNT=$((COUNT+1))
+					done
 
-    if [ "$DEV0" -gt 0 ]; then
-        logger -t switch3g[$PID] "3G MODEM ready - using cdc-acm module"
+					$LOGS "3G MODEM FOUND - $SWITCH - switching ..."
 
-        nvram set 3g_module=cdc-acm
-        return 1
+					/usr/sbin/usb_modeswitch -Q -c /etc/usb_modeswitch.d/$SWITCH -v $DV -p $DP -b $DB -g $DG
 
-    elif [ "$DEV1" -gt 0 ]; then
-        logger -t switch3g[$PID] "3G MODEM ready - using option module"
+					# need few seconds before modem will be detected once again after switch
+					COUNT=1
+					while [ "$COUNT" -lt 15 ]; do
+						sleep 1
+						[ -s $PATHDEV/bNumInterfaces ] && {
+							[ "$(cat "$PATHDEV"/bNumInterfaces)" -gt "$IFN_BEFORE" ] && break
+						}
+						COUNT=$((COUNT+1))
+					done
+					sleep 1
 
-        nvram set 3g_module=option
-        return 1
+					VENDOR=$(cat /etc/usb_modeswitch.d/"$SWITCH" | grep TargetVendor | cut -d "=" -f2 | cut -d "x" -f2)
+					[ -z "$VENDOR" ] && VENDOR=$(cat "$PATHDEV"/idVendor)
 
-    elif [ "$DEV2" -gt 0 ]; then
-        logger -t switch3g[$PID] "3G MODEM ready - using sierra module"
+					PRODUCT=$(cat "$PATHDEV"/idProduct)
+					[ -n "$PRODUCT" ] && {
+						$LOGS "3G MODEM ready - $VENDOR:$PRODUCT"
+						SWITCHED=1
+						break
+					}
+				}
+			}
+		done
 
-        nvram set 3g_module=sierra
-        return 1
+		[ "$SWITCHED" -eq 0 ] && {
+			$LOGS "3G MODEM not found in USB_ModeSwitch database - already switched? Loading modules..."
+		}
+	}
+}
 
-    else
-        logger -t switch3g[$PID] "3G MODEM not found by cdc-acm, option or sierra module. Trying usbserial ..."
+searchDiag() {
+	local MODULES="cdc-acm option sierra"
+	local IS_MLOADED=0 ALRTXT="" MODULE
+	local PATHDIAG="/sys/bus/usb/devices"
 
-        #modprobe -r cdc_acm //we can`t do that. I don`t know why...
-        modprobe -r sierra
-        modprobe -r option
-        modprobe -r cdc-acm
+	[ -z "$VENDOR" ] && VENDOR=$(cat "$PATHDIAG"/"$DEVICENAME"/idVendor)
+	[ -z "$PRODUCT" ] && PRODUCT=$(cat "$PATHDIAG"/"$DEVICENAME"/idProduct)
 
-        IS_VENDOR=`echo $VENDOR | wc -w`
-        if [ "$IS_VENDOR" -gt 0 ]; then
-            IS_PRODUCT=`echo $PRODUCT | wc -w`
+	[ -z "$TTYS" ] && {
+		for MODULE in $MODULES; do
+			modprobe $MODULE
+			sleep 1
 
-            if [ "$IS_PRODUCT" -gt 0 ]; then
-                logger -t switch3g[$PID] "3G MODEM - loading module usbserial"
-                modprobe -r usbserial
-                sleep 1
-                insmod usbserial vendor=0x$VENDOR product=0x$PRODUCT
-                echo "$VENDOR:$PRODUCT" > $DETECTFILE
-                sleep 2
-            fi
-        fi
+			TTYS=$(ls -d $PATHDIAG/$DEVICENAME/${DEVICENAME}*/tty?* 2>/dev/null | sed -e "s/.*\/\//.*/g" -e "s/.*\//\/dev\//g" | tr "\n" " " | sed -e "s/  */ /g" -e "s,^ *,,; s, *$,,")
+			[ -z "$TTYS" ] && {
+				$LOGS "3G MODEM ($MODULE) not found ..."
+				modprobe -r $MODULE
+				sleep 1
+			} || {
+				# found
+				break
+			}
+		done
 
-        DEV=`cat /proc/bus/usb/devices | grep Driver | grep usbserial | wc -l`
-        if [ "$DEV" -gt 0 ]; then
-            logger -t switch3g[$PID] "3G MODEM ready - using usbserial module [1]"
-            nvram set 3g_module=usbserial
-            return 1
-        elif [ -f $DETECTFILE ]; then
-            VENDOR=`cat $DETECTFILE | cut -d ":" -f1`
-            PRODUCT=`cat $DETECTFILE | cut -d ":" -f2`
-            TEST3=`lsusb | grep $VENDOR | grep $PRODUCT | wc -l`
+		[ -n "$TTYS" ] && {
+			$LOGS "3G MODEM found - using $MODULE module"
+		} || {
+			$LOGS "3G MODEM not found by cdc-acm, option, sierra module. Trying usbserial ..."
 
-            if [ "$TEST3" == "1" ]; then
-                logger -t switch3g[$PID] "3G MODEM FOUND - already switched - Last known $VENDOR:$PRODUCT"
+			TTYS=$(ls -d $PATHDIAG/$DEVICENAME/${DEVICENAME}*/tty?* 2>/dev/null | sed -e "s/.*\/\//.*/g" -e "s/.*\//\/dev\//g" | tr "\n" " " | sed -e "s/  */ /g" -e "s,^ *,,; s, *$,,")
+			[ -z "$TTYS" ] && {
+				$LOGS "3G MODEM - loading usbserial module ($VENDOR:$PRODUCT)"
+				IS_MLOADED=$(lsmod | grep usbserial | wc -l)
 
-                DEV=`cat /proc/bus/usb/devices | grep Driver | grep usbserial | wc -l`
-                if [ "$DEV" -gt 0 ]; then
-                    logger -t switch3g[$PID] "3G MODEM ready - using usbserial module [2]"
-                    nvram set 3g_module=usbserial
-                    return 1
-                else
-                    logger -t switch3g[$PID] "3G MODEM - loading usbserial module"
-                    modprobe -r usbserial
-                    sleep 1
-                    insmod usbserial vendor=0x$VENDOR product=0x$PRODUCT
-                    echo "$VENDOR:$PRODUCT" > $DETECTFILE
-                    nvram set 3g_module=usbserial
-                    return 1
-                fi
-            fi
-        else
-            #last chance. try to load usbserial for each usb device
-            DEVICES=`lsusb | awk '{print $6}'`
+				[ "$IS_MLOADED" -gt 0 ] && {
+					echo "$VENDOR $PRODUCT" > /sys/bus/usb-serial/drivers/generic/new_id
+				} || {
+					insmod usbserial vendor=0x$VENDOR product=0x$PRODUCT
+				}
+				sleep 1
 
-            for SWITCH in $DEVICES; do
+				TTYS=$(ls -d $PATHDIAG/$DEVICENAME/${DEVICENAME}*/tty?* 2>/dev/null | sed -e "s/.*\/\//.*/g" -e "s/.*\//\/dev\//g" | tr "\n" " " | sed -e "s/  */ /g" -e "s,^ *,,; s, *$,,")
+				[ -n "$TTYS" ] && {
+					MODULE="usbserial"
+				}
+			}
+		}
+	}
 
-                VENDOR=`echo $SWITCH | cut -d ":" -f1`
-                PRODUCT=`echo $SWITCH | cut -d ":" -f2`
-                modprobe -r usbserial
-                sleep 1
-                insmod usbserial vendor=0x$VENDOR product=0x$PRODUCT
-                sleep 2
+	[ -z "$TTYS" ] && {
+		nvram set "$PREFIX"_modem_modules=""
+		wayOut "3G MODEM not found - connection process terminated!"
+	} || {
+		[ "$ALREADYFOUND" -eq 0 ] && $LOGS "3G MODEM ready - DIAG interface(s) found ("$TTYS")"
 
-                DEV=`cat /proc/bus/usb/devices | grep Driver | grep usbserial | wc -l`
+		echo $TTYS > $DIAGSFILE
+		nvram set "$PREFIX"_modem_modules="$MODULE"
+	}
+}
 
-                if [ "$DEV" -gt 0 ]; then
-                    logger -t switch3g[$PID] "3G MODEM ready - using usbserial module [3]"
-                    nvram set 3g_module=usbserial
-                    echo "$VENDOR:$PRODUCT" > $DETECTFILE
-                    return 1
-                fi
-            done
-        fi
-    fi
-    return 0
+findPath() {
+	if [ "$MODULE" == "cdc-acm" ]; then
+		MPATH="/sys/bus/usb/drivers/cdc_acm/new_id"
+	elif [ "$MODULE" == "option" ]; then
+		MPATH="/sys/bus/usb-serial/drivers/option1/new_id"
+	elif [ "$MODULE" == "sierra" ]; then
+		MPATH="/sys/bus/usb-serial/drivers/sierra/new_id"
+	elif [ "$MODULE" == "usbserial_generic" ]; then
+		MPATH="/sys/bus/usb-serial/drivers/generic/new_id"
+		MODULE="usbserial"
+	else
+		MPATH="/dev/null"
+	fi
 }
 
 setPIN() {
-    PIN=`nvram get "$PREFIX"_modem_pin`
-    IS_PIN=`nvram get "$PREFIX"_modem_pin | wc -w`
+	local PIN=$(nvram get "$PREFIX"_modem_pin)
+	local IS_PIN=$(nvram get "$PREFIX"_modem_pin | wc -w)
+	local IS_DONE=0 PINVAL DEVALL i
 
-    if [ "$IS_PIN" == "1" ]; then
-        PINCODE="$PIN" gcom -d /dev/$DEVNR -s /etc/gcom/setpin.gcom
-    fi
-}
+	[ "$IS_PIN" -eq 1 ] && {
+		DEVALL="$DEVNR $(cat "$DIAGSFILE" | sed "s~"$DEVNR"~~")"
 
-checkPid() {
-    if [ -f $PIDFILE ]; then
+		for i in $DEVALL; do	# find working interface
+			[ -z $(MODE="ATI" gcom -d "$i" -s /etc/gcom/setverbose.gcom | grep "OK" | tr -d '\r') ] && {
+				sleep 2
+				continue
+			}
 
-        PIDNO=$(cat $PIDFILE)
-        cat "/proc/$PIDNO/cmdline" > /dev/null 2>&1
+			PINVAL=$(PINCODE="$PIN" gcom -d "$i" -s /etc/gcom/setpin.gcom)
+			[ "$(echo "$PINVAL" | grep successfully | wc -l)" -eq 1 ] && {
+				IS_DONE=1
+			}
+			# try only once on working interface (do not lock the sim)
+			break
+		done
+	}
 
-        if [ $? -eq 0 ]; then
-            logger -t switch3g[$PID] "3G MODEM - another proces in action - exiting"
-            exit 0
-        else
-            # Process not found assume not running
-            echo $PID > $PIDFILE
-            if [ $? -ne 0 ]; then
-                logger -t switch3g[$PID] "3G MODEM - could not create PID file"
-                exit 0
-            fi
-        fi
-    else
-        echo $PID > $PIDFILE
-        if [ $? -ne 0 ]; then
-            logger -t switch3g[$PID] "3G MODEM - could not create PID file"
-            exit 0
-        fi
-    fi
+	[ "$IS_PIN" -eq 1 -a "$IS_DONE" -ne 1 ] && {
+		watchdog del
+		wayOut "3G MODEM - SIM locked - connection process terminated!"
+	} || {
+		$LOGS "3G MODEM - SIM ready"
+	}
 }
 
 signal() {
-    #check signal strength
-    CSQ=`gcom -d /dev/$DEVNR -s /etc/gcom/getstrength.gcom | grep "CSQ:" | cut -d " " -f2 | cut -d "," -f1`
-    DBM=$((-113+CSQ*2))
-    logger -t switch3g[$PID] "3G MODEM Signal Strength: $DBM dBm"
+	local CSQ RSSI
+
+	CSQ=$(gcom -d "$DEVNR" -s /etc/gcom/getstrength.gcom 2>/dev/null | tr -d '\r')
+
+	[ "$(echo "$CSQ" | grep OK | wc -l)" -eq 1 ] && {
+		CSQ=$(echo "$CSQ" | grep "CSQ:" | cut -d " " -f2 | cut -d "," -f1)
+		RSSI=$((-113+CSQ*2))
+		$LOGS "3G MODEM Signal Strength: $RSSI dBm"
+		nvram set "$PREFIX"_modem_signal="$RSSI"
+	}
+}
+
+checkPid() {
+	local PRIORITY="$1" PIDNO
+
+	[ -f $PIDFILE ] && {
+		PIDNO=$(cat $PIDFILE)
+		cat "/proc/$PIDNO/cmdline" > /dev/null 2>&1
+
+		[ $? -eq 0 ] && {
+			$LOGS "3G MODEM - another process in action - exiting"
+			exit 0
+		} || {
+			[ "$PRIORITY" -eq 0 ] && return
+			# Process not found assume not running
+			echo $PID > $PIDFILE
+			[ $? -ne 0 ] && {
+				$LOGS "3G MODEM - could not create PID file"
+				exit 0
+			}
+		}
+	} || {
+		[ "$PRIORITY" -eq 0 ] && return
+		echo $PID > $PIDFILE
+		[ $? -ne 0 ] && {
+			$LOGS "3G MODEM - could not create PID file"
+			exit 0
+		}
+	}
+}
+
+wayOut() {
+	local TEXT="$1"
+	[[ -z $TEXT ]] && TEXT="3G Modem - exiting"
+
+	$LOGS "$TEXT"
+	rm -f $PIDFILE > /dev/null 2>&1
+	exit 0
 }
 
 
 ###################################################
 
 
-#check pid file
-checkPid
+[ "$2" == "signal" ] && {
+	checkPid 0
+	signal
+} || {
+	checkPid 1
+	switchMode
+	searchDiag
+	setPIN
+	signal
+	service $PREFIX restart
+}
 
-# detect modem
-switchMode
-
-if [ $? -eq 1 ]; then
-    setPIN
-    signal
-    service $PREFIX restart
- else
-    logger -t switch3g[$PID] "3G MODEM not found ..."
-fi
-
-#remove pid file
 rm -f $PIDFILE > /dev/null 2>&1
